### ISSUE TITLE
Horizontal section

### ISSUE THREAD

**Issue by Rungee** [GIScience/Leaflet.Heightgraph#29]
Add an option to control a horizontal section (see image below).
The parts of a route which lie above or below the specified value (400m) are drawn in different colors.

![image](https://cloud.githubusercontent.com/assets/1660719/22427075/01dafeda-e702-11e6-8bd7-5d559fef3235.png)

**Comment by TimMcCauley** [comment]
Great idea, we will work on this after the first release

**Comment by Kinas** [comment]
What do you think about a draggable item (e.g. triangle) on the y axis that controls the horizontal section? With a click on the triangle the line could appear and disappear. See picture below.
![idea](https://user-images.githubusercontent.com/15326489/28789261-e5b2b9c0-7624-11e7-8fbd-e361df768718.jpeg)

**Comment by TimMcCauley** [comment]
Let's go ahead 👍

**Comment by Rungee** [comment]
nice :) I would move the draggable element to the right side, so altitude values are not overlapped.
