### ISSUE TITLE
margins get counted double

### ISSUE THREAD

**Issue by cdauth** [GIScience/Leaflet.Heightgraph#33]
In this code:

```javascript
this._width = this.options.width - this._margin.left - this._margin.right;
this._height = this.options.height - this._margin.top - this._margin.bottom;
this._mappings = this.options.mappings;
this._svgWidth = this._width - this._margin.left - this._margin.right;
this._svgHeight = this._height - this._margin.top - this._margin.bottom;
var svg = this._svg = d3.select(this._container)
    .append("svg")
    .attr("width", this._svgWidth + this._margin.left + this._margin.right)
    .attr("height", this._svgHeight + this._margin.top + this._margin.bottom)
```

the margin gets counted double. The resulting SVG element should have the width and height specified in the options, but instead `_width` has the margins subtracted from `options.width`, and then `_svgWidth` has then subtracted a second time (and they get then added again).

`_width` and `_height` should be set to whatever is set in the options, without subtracting the margins.

A workaround is to increase width and height in the specified options by adding the margin to them.

**Comment by TimMcCauley** [comment]
@cdauth thank you. This repository is currently not maintained due to lack of resources - feel free to pull request, I will accept.
