### ISSUE TITLE
Package on npm

### ISSUE THREAD

**Issue by boldtrn** [GIScience/Leaflet.Heightgraph#36]
I just wanted to try this package locally. [I couldn't find it on npm](https://www.npmjs.com/search?q=leaflet.heightgraph). Is it named differently or is it simply missing from npm?

If it's missing, would you mind if I publish it? This would make using this plugin a lot easier :).

**Comment by TimMcCauley** [comment]
Hey @boldtrn , sure; feel free. We currently have no maintainer as this was a project from one of our students a while ago but it certainly has some potential. Shall I invite you as a collaborator for this project?

**Comment by boldtrn** [comment]
Hey @TimMcCauley thanks for the offer, yes please :). Currently, my time is pretty limited but I do have a couple of ideas for this project. So I will try to add some of these and publish it on npm.

**Comment by boldtrn** [comment]
[I uploaded this repo to npm](https://www.npmjs.com/package/leaflet.heightgraph).

**Comment by boldtrn** [comment]
> Shall I invite you as a collaborator for this project?

Any updates on this? I would be still curious to add a couple of improvements/changes to this project or would you prefer if I create a fork and potentially merge some of the changes later on?

**Comment by TimMcCauley** [comment]
Sorry @boldtrn this completely left my radar.. just invited you with maintainer rights. Sorry for the delay...!!!
