### ISSUE TITLE
Replace Data

### ISSUE THREAD

**Issue by boldtrn** [GIScience/Leaflet.Heightgraph#37]
Is there a way to replace the data shown in the heightgraph?

Currently, my approach is to remove the heigthgraph and readd it to the map when the data changes.

With MrMufflon/Leaflet.Elevation there was the option to clear the data and then readd it. It's possible to call the `addData`function several times with heightgraph, but with every call it will toggle the visibility/show state.

**Comment by jaluebbe** [comment]
My workaround is to use the option "expand: false" for L.control.heightgraph. Now, I could open the heightgraph by clicking the icon. If I replace data, the heightgraph is replaced and stays in its expand state. Data is replaced by calling hg.addData(geojson). The geojson Layer showing the track is cleared before new data is added.

**Comment by TheGreatRefrigerator** [comment]
Closed in #91
