### ISSUE TITLE
Can't toggle on mobile device

### ISSUE THREAD

**Issue by boldtrn** [GIScience/Leaflet.Heightgraph#40]
Using an Android with Chrome the toggle button does not work. There is [some handling](https://github.com/GIScience/Leaflet.Heightgraph/blob/master/src/L.Control.Heightgraph.js#L63) in the code for this already.

**Comment by boldtrn** [comment]
The issue seems to be related to this code block:
```
if (!L.Browser.android) {
  L.DomEvent.on(this._button, 'click', this._expand, this);
  L.DomEvent.on(this._closeButton, 'click', this._expand, this);
}
```

Is there any reason why the buttons are not enabled for Android browsers or can we remove the `if`?

**Comment by TimMcCauley** [comment]
@boldtrn I don't think so - feel free to remove ;-)
