### ISSUE TITLE
Horizontal drag line snaps back to the bottom

### ISSUE THREAD

**Issue by boldtrn** [GIScience/Leaflet.Heightgraph#42]
Every time you want to move the horizontal drag line, it snaps down to the bottom,

How to reproduce.
Drag the horizontal drag line to a value. Now try to drag it to a different value, it snaps down to the bottom and you have to move it back from there.

**Comment by TheGreatRefrigerator** [comment]
fixed in 6689f3677280110332b48fd3be5e961213891a48
