### ISSUE TITLE
Adding to leaflet plugins

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/Leaflet.Heightgraph#54]
We could get this plugin listed on https://leafletjs.com/plugins.html - what do you think @boldtrn ?

**Comment by TimMcCauley** [comment]
We could add you as the maintainer.

**Comment by boldtrn** [comment]
Sounds good, that's a great idea :).

**Comment by TimMcCauley** [comment]
@boldtrn let's see ;-) https://github.com/Leaflet/Leaflet/pull/6731

**Comment by boldtrn** [comment]
Awesome, thanks @TimMcCauley!

**Comment by TheGreatRefrigerator** [comment]
listed in 
https://github.com/Leaflet/Leaflet/pull/6731
