### ISSUE TITLE
Prefix class names

### ISSUE THREAD

**Issue by boldtrn** [GIScience/Leaflet.Heightgraph#65]
Currently many class names do have rather weak names, see #64.

I think it would be good to prefix all classes with `leaflet-heightgraph-[classname]` or something like that? 

On [Kurviger](https://kurviger.de/) I just had a css conflict with Bootstrap, which is a common CSS framework.

**Comment by TheGreatRefrigerator** [comment]
Seems like automatic closing doesn't work if the pull request is not going into master ...
