### ISSUE TITLE
Fix security Issues

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/Leaflet.Heightgraph#66]
There are some vulnerabilities that need to be fixed.
You can see them in the Security tab if you have the rights or fork it and view them.
Security alerts have to be enabled in the repository settings.

**Comment by boldtrn** [comment]
Yes that's correct. However, these are only dev dependencies. So there should be no security issues upstream?

**Comment by TheGreatRefrigerator** [comment]
yes, you are right, except for vulnerabilities in d3 and leaflet there are no issues for end users.
Still for our local dev environment, since we switched to KTA internal network, we want to reduce security risks.
I will deal with this ;)

**Comment by TheGreatRefrigerator** [comment]
fixed in d206f3d7c93857a1b0807c51146a7455e13f2219
