### ISSUE TITLE
Use babel

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/Leaflet.Heightgraph#70]

**Comment by TheGreatRefrigerator** [comment]
fixed in d5867b76387ec2aff61a5883bcaedfcd8fc2c898

**Comment by boldtrn** [comment]
Thanks for looking into this! I will have to try this soon :). :tada: :tada: 

BTW: Should we close here then?

**Comment by TheGreatRefrigerator** [comment]
I will close once it's on master branch with a new release.
Forgot to reference in the commit -.-
