### ISSUE TITLE
Crossing -90 Longitude

### ISSUE THREAD

**Issue by zzptichka** [GIScience/Leaflet.Heightgraph#71]
When route crosses -90 Longitude heightraph shows some crazy data. 
Even the shortest 100-meter route shows as 120000 km long

**Comment by TheGreatRefrigerator** [comment]
@zzptichka 
could you provide a specific example please.
I couldn't reproduce this up till now:
http://maps.openrouteservice.org/directions?n1=32.292357&n2=-90.190887&n3=10&a=32.240683,-89.989014,32.379961,-90.351563&b=0&c=0&k1=en-US&k2=km

http://maps.openrouteservice.org/directions?n1=32.292357&n2=-90.190887&n3=10&a=32.379961,-90.351563,32.240683,-89.989014&b=0&c=0&k1=en-US&k2=km

which version of the Leaflet.Heightgraph are you currently using ?

**Comment by zzptichka** [comment]
I think this might be a problem with my data. I'll close the issue and re-open if I can confirm it.
