### ISSUE TITLE
Resizing the graph

### ISSUE THREAD

**Issue by Khristil** [GIScience/Leaflet.Heightgraph#78]
Hi,
It would be convenient to resize the graph in order to adjust a website to different screen size.
I added a method to Heightgraph:

 //  method to resize the graph
  size: function size(swh) {
	  if (swh[0].w){
		  this.options.width  = swh[0].w;
	  }
	  if (swh[0].h){
		  this.options.height = swh[0].h;
	  }
	  this._init_options();
	  d3.select(this._container).select('svg')
		  .attr("width", this._svgWidth + this._margin.left + this._margin.right)
		  .attr("class", "heightgraph-container")
		  .attr("width", this._svgWidth + this._margin.left + this._margin.right)
		  .attr("height", this._svgHeight + this._margin.top + this._margin.bottom);
  },
    
  // usage:
  // var hg = L.control.heightgraph();
  // hg.addTo(map);
....
  //	if (hg){
  //	    hg.size([{"w":700,"h":250}])
  //		hg.addData(geodata)
  //	}

Regards

**Comment by boldtrn** [comment]
Thanks, would you mind to create a PR for this?

**Comment by Khristil** [comment]
I' m not  enough comfortable with this tool to do that.
   
  
  
   BR
   
  
  
   Le 21 avril 2020 à 12:48, Robin <notifications@github.com> a écrit : 
   
   
   
   Thanks, would you mind to create a PR for this?

**Comment by TheGreatRefrigerator** [comment]
coming soon

**Comment by mrubli** [comment]
@TheGreatRefrigerator I had started working on this a couple of weeks ago before your "coming soon" announcement. Here's a PR for this feature: https://github.com/GIScience/Leaflet.Heightgraph/pull/84

Performance of "real-time" resizing isn't great on slower machines but fixing that would likely require refactoring that I'm not comfortable with. If you have a cleaner solution than this feel free to ignore the PR.

**Comment by mrubli** [comment]
@TheGreatRefrigerator Can we close this now that https://github.com/GIScience/Leaflet.Heightgraph/pull/84 is merged?

**Comment by TheGreatRefrigerator** [comment]
Will be closed, once it is in master.

**Comment by Khristil** [comment]
Yes, this issue #84 can be closed,
Thanks

**Comment by TheGreatRefrigerator** [comment]
Closed with #84
