### ISSUE TITLE
Arrows for selection of FeatureCollection disappear when resize() is called

### ISSUE THREAD

**Issue by jaluebbe** [GIScience/Leaflet.Heightgraph#92]
I opened a JS console for https://giscience.github.io/Leaflet.Heightgraph/ and called 
hg.resize({width: window.innerWidth*0.98}); to make the graph fit the window. The selection arrows (surface, waytype, ...) disappeared. When calling resize a second time, the arrows reappeared.

**Comment by TheGreatRefrigerator** [comment]
I just confirmed this and found another bug as well, when you only specify either width or height.

**Comment by TheGreatRefrigerator** [comment]
Was probably linked to https://github.com/GIScience/Leaflet.Heightgraph/issues/93.
Seems to work with new fixes
